spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit_user
    password: rabbit_password

myRabbit:
  queueName: test-queue-name
  routingName: test-routing-name
  exchangeName: test-exchange-name